project_id = "ezvwyfqtyanwnoyymhav"

[functions.browser-automation]
verify_jwt = true

[functions.simple-tos-check]
verify_jwt = false

[functions.tos-monitor]
verify_jwt = false

[functions.fast-camp-search]
verify_jwt = false

[functions.environment-check]
verify_jwt = false

[functions.create-payment-setup]
verify_jwt = true

[functions.capture-success-fee]
verify_jwt = false

[functions.reserve-callback]
verify_jwt = false

[functions.reserve-execute]
verify_jwt = false

[functions.sms-send]
verify_jwt = false

[functions.sms-verify]
verify_jwt = false

[functions.save-readiness]
verify_jwt = true

[functions.preflight-check]
verify_jwt = true

[functions.twilio-config-status]
verify_jwt = false

[functions.twilio-status-callback]
verify_jwt = false

[functions.register-session]
verify_jwt = false

[functions.create-setup-session]
verify_jwt = true

[functions.process-registration-success]
verify_jwt = true

[functions.process-registrations-cron]
verify_jwt = false

[functions.charge-registration]
verify_jwt = false

[functions.send-email-sendgrid]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.activation-status]
verify_jwt = true

[functions.create-embedded-checkout]
verify_jwt = true

[functions.finalize-activation]
verify_jwt = true

[functions.twilio-inbound]
verify_jwt = false

[functions.delete-provider-credentials]
verify_jwt = true

[functions.watch-signup-open]
verify_jwt = false

[functions.test-adaptive-polling]
verify_jwt = false

[functions.schedule-from-readiness]
verify_jwt = true

[functions.notify-parent]
verify_jwt = false

[functions.otp-submit]
verify_jwt = false

[functions.captcha-complete]
verify_jwt = false

[functions.approval-submit]
verify_jwt = false

[functions.get-payment-summary]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.reserve-init]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.extract-session]
verify_jwt = false

[functions.schedule-text-verification-reminders]
verify_jwt = true

[functions.send-text-verification-reminders]
verify_jwt = false

[functions.create-approval-workflow]
verify_jwt = false

[functions.process-approval]
verify_jwt = false

[functions.debug-browser-setup]
verify_jwt = false

[functions.test-browser-init]
verify_jwt = false

[functions.test-browserbase-direct]
verify_jwt = false

[functions.test-browser-automation]
verify_jwt = false

[functions.ai-context-manager]
verify_jwt = true

[functions.test-vision-analysis]
verify_jwt = false

[functions.intelligent-model-selector]
verify_jwt = false

[functions.test-minimal]
verify_jwt = false

[functions.analyze-captcha-challenge]
verify_jwt = false

[functions.browser-automation-simple]
verify_jwt = false

