project_id = "ezvwyfqtyanwnoyymhav"

[functions.register-session]
verify_jwt = false

[functions.create-setup-session]
verify_jwt = true

[functions.process-registration-success]
verify_jwt = true

[functions.process-registrations-cron]
verify_jwt = false

[functions.charge-registration]
verify_jwt = false

[functions.send-email-sendgrid]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.activation-status]
verify_jwt = true

[functions.create-embedded-checkout]
verify_jwt = true
