# GitHub Dependabot configuration for automatic dependency updates
version: 2

updates:
  # Enable version updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@dependabot"
    assignees:
      - "@dependabot"
    # Security updates will be applied immediately
    allow:
      - dependency-type: "all"
    # Automatically merge patch and minor updates for dev dependencies
    auto-merge: true
    # Group related dependencies
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      ui:
        patterns:
          - "@radix-ui/*"
          - "tailwindcss*"
          - "lucide-react"
      supabase:
        patterns:
          - "@supabase/*"
          - "supabase"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5

  # Enable version updates for Docker if present
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5