-- Create a test YMCA session for testing the automated signup page
INSERT INTO public.sessions (
  id,
  title,
  name,
  source_url,
  signup_url,
  start_at,
  end_at,
  location,
  location_city,
  location_state,
  age_min,
  age_max,
  price_min,
  price_max,
  capacity,
  spots_available,
  availability_status,
  platform,
  provider_id,
  created_at,
  updated_at
) VALUES (
  '6bc42c98-3c9c-4bec-a538-e277d156ed62'::uuid,
  'YMCA Summer Adventure Camp',
  'Summer Adventure Camp - Week 1',
  'https://www.ymcacamp.org/register',
  'https://www.ymcacamp.org/register',
  '2025-07-08 09:00:00'::timestamptz,
  '2025-07-12 15:00:00'::timestamptz,
  'YMCA of Greater Seattle - Northgate Branch',
  'Seattle',
  'WA',
  6,
  12,
  225,
  275,
  20,
  8,
  'open',
  'YMCA',
  '550e8400-e29b-41d4-a716-446655440001'::uuid,
  now(),
  now()
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  source_url = EXCLUDED.source_url,
  platform = EXCLUDED.platform,
  updated_at = now();