name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # Can also run manually

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          # Check if package-lock.json exists, if not create it
          if [ ! -f package-lock.json ]; then
            echo "⚠️ No package-lock.json found. This should be generated locally and committed."
            echo "📝 Generating package-lock.json in CI as fallback..."
            npm install --legacy-peer-deps
          else
            echo "✅ Using existing package-lock.json"
            npm ci
          fi
      - run: npx playwright install --with-deps
      - name: Build and test
        run: |
          npm run build
          npm run preview &
          sleep 5
          npm run test:mvp
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
