name: E2E Tests

on:
  workflow_dispatch:  # Only manual for now
  # push:
  #   branches: [ main ]
  # pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          # Create .npmrc to prevent any ci behavior
          echo "package-lock=false" > .npmrc
          echo "fund=false" >> .npmrc
          echo "audit=false" >> .npmrc
          echo "legacy-peer-deps=true" >> .npmrc
          
          # Force npm install without any lockfile behavior
          npm install --legacy-peer-deps --no-package-lock --no-fund --no-audit
          echo "✅ Dependencies installed successfully"
      - run: npx playwright install --with-deps
      - name: Build and test
        run: |
          npm run build
          npm run preview &
          sleep 5
          npm run test:mvp
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
