name: E2E Tests

on:
  push:
    branches: [ main ]   # run on pushes to main
  pull_request:          # run on PRs targeting main
  schedule:
    - cron: "0 5 * * *"  # run daily at 05:00 UTC (midnight EST)

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clean install dependencies
        run: |
          # Create .npmrc for better resolution
          cat > .npmrc << EOF
          legacy-peer-deps=true
          fund=false
          audit=false
          prefer-offline=true
          maxsockets=1
          registry=https://registry.npmjs.org/
          EOF
          
          # Remove any existing files that might cause conflicts
          rm -rf node_modules package-lock.json
          
          # Clear npm cache
          npm cache clean --force
          
          # Install with maximum compatibility flags
          npm install --legacy-peer-deps --no-audit --no-fund --maxsockets=1
      - run: npx playwright install --with-deps
      - run: npm run test:mvp
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
