name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # Can also run manually

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: |
          # If no package-lock.json exists, create one
          if [ ! -f package-lock.json ]; then
            echo "No package-lock.json found, generating one..."
            npm install --legacy-peer-deps
          else
            echo "Using existing package-lock.json..."
            npm ci --legacy-peer-deps
          fi
      - run: npx playwright install --with-deps
      - name: Build and test
        run: |
          npm run build
          npm run preview &
          sleep 5
          npm run test:mvp
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
