# Security scanning workflow for CodeQL analysis and dependency scanning
name: "Security Scanning"

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  schedule:
    - cron: '30 2 * * 1'  # Run weekly on Mondays at 2:30 AM UTC

jobs:
  codeql:
    name: "CodeQL Analysis"
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'typescript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: security-extended,security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  dependency-scan:
    name: "Dependency Vulnerability Scan"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Create .npmrc for better resolution
      run: |
        cat > .npmrc << EOF
        legacy-peer-deps=true
        fund=false
        audit=false
        prefer-offline=true
        maxsockets=1
        registry=https://registry.npmjs.org/
        EOF

    - name: Robust dependency installation
      run: |
        # Remove any existing files that might cause conflicts
        rm -rf node_modules package-lock.json
        
        # Clear npm cache completely
        npm cache clean --force
        
        # Install with maximum compatibility flags
        npm install --legacy-peer-deps --no-audit --no-fund --maxsockets=1 --progress=false
        
        # Verify installation
        npm list --depth=0 || echo "Some peer dependency warnings expected"

    - name: Run npm audit (informational only)
      run: |
        echo "Running npm audit for informational purposes..."
        npm audit --audit-level=high --json > audit-results.json || true
        if [ -s audit-results.json ]; then
          echo "Audit found issues, but continuing..."
          cat audit-results.json | jq '.vulnerabilities | length' || echo "No critical vulnerabilities parser available"
        else
          echo "Audit completed successfully"
        fi
      continue-on-error: true

    - name: Security check with alternative approach
      run: |
        echo "Performing basic security checks..."
        
        # Check for known vulnerable packages in package.json
        if grep -E "(event-stream|flatmap-stream)" package.json; then
          echo "⚠️ Found potentially vulnerable packages"
        fi
        
        # Check for outdated critical packages
        npm outdated --json > outdated.json || true
        if [ -s outdated.json ]; then
          echo "Found outdated packages:"
          cat outdated.json | jq '.[] | select(.type == "dependencies")' || echo "Some packages may be outdated"
        fi
      continue-on-error: true

  security-headers:
    name: "Security Headers Check"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for HTTP URLs in codebase
      run: |
        echo "Checking for insecure HTTP URLs..."
        if grep -r "http://" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" --exclude="*.svg" .; then
          echo "❌ Found insecure HTTP URLs in codebase"
          exit 1
        else
          echo "✅ No insecure HTTP URLs found"
        fi

    - name: Check for hardcoded secrets
      run: |
        echo "Checking for potential hardcoded secrets..."
        # Look for actual API keys and secrets, not error message text
        if grep -r -E "(sk_[a-zA-Z0-9]{30,}|pk_[a-zA-Z0-9]{30,})" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/ || \
           grep -r -E "api[_-]?key\s*[=:]\s*['\"][a-zA-Z0-9]{20,}['\"]" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/ || \
           grep -r -E "const\s+\w*[Ss]ecret\s*[=:]\s*['\"][a-zA-Z0-9]{20,}['\"]" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/; then
          echo "❌ Potential hardcoded secrets found"
          exit 1
        else
          echo "✅ No obvious hardcoded secrets found"
        fi

  supabase-security:
    name: "Supabase Security Check"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check Supabase Configuration
      run: |
        echo "Checking Supabase configuration security..."
        
        # Check for public functions without JWT verification
        if grep -r "verify_jwt.*false" supabase/config.toml; then
          echo "⚠️ Found public functions (verify_jwt = false). Ensure these are intentional."
        fi
        
        # Check for proper RLS policies (basic check)
        if find supabase/migrations -name "*.sql" -exec grep -l "CREATE POLICY" {} \; | wc -l | awk '{if($1==0) exit 1}'; then
          echo "✅ RLS policies found in migrations"
        else
          echo "⚠️ No RLS policies found. Ensure Row Level Security is properly configured."
        fi
        
        echo "✅ Supabase security check completed"